# Generated by Django 3.0.8 on 2020-07-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_name',
        ),
    ]
